export const posts: Post[] = [
  {
    "id": 1,
    "image": "https://images.unsplash.com/photo-1618506429948-1746e6e8093f?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "text": `In a world filled with distractions, the simple pleasure of reading a good book can offer a much-needed escape. Whether you’re curling up with a classic novel or diving into the latest bestseller, there’s something truly magical about getting lost in a story. Our latest collection of books offers something for everyone, from gripping thrillers to heartwarming romances, thought-provoking non-fiction, and beyond. At our online bookstore, we believe that reading is more than just a pastime—it’s a journey. It allows you to explore new worlds, experience different cultures, and understand diverse perspectives. That’s why we’ve carefully curated our selection to include a wide variety of genres, ensuring that every reader finds something they love. Take a moment to browse our latest arrivals and discover your next great read. Whether you’re looking for an epic adventure or a quiet, reflective read, we have something that will resonate with you. Books can change your life, open your mind to new possibilities, and provide comfort in times of need. In today’s fast-paced world, we all need a little time to ourselves, and what better way to spend it than with a book that speaks to your soul?`,
    "date": "2022-01-01",
    "lesson_num": 1,
    "title": "Discover Your Next Great Read",
    "author": "John Doe",
    "popular": true,
    "favorites": false,
    "likesCount": 10,
    "dislikesCount": 1,
    "isLiked": true,
    "isDisliked": false
  },
  {
    "id": 2,
    "image": "https://images.unsplash.com/photo-1524578271613-d550eacf6090?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "text": "Dive into the world of mystery and suspense with our top picks this week. Whether you're a fan of classic whodunits or modern psychological thrillers, our selection has something for every mystery lover. Mysteries have a unique way of captivating the mind and keeping you on the edge of your seat. The thrill of piecing together clues, uncovering secrets, and solving the puzzle before the final page is turned is unmatched. Our collection features works from some of the most renowned mystery writers, whose stories have stood the test of time. From the foggy streets of Victorian London to the dark alleys of modern-day cities, these tales of intrigue and suspense are perfect for those who love to be kept guessing. The mysteries we’ve selected will challenge your intellect, test your deductive reasoning, and satisfy your craving for a gripping narrative. Each story is a journey into the unknown, where every character could be hiding something, and every detail could be a clue. Are you ready to solve the mystery?",
    "date": "2022-01-02",
    "lesson_num": 2,
    "title": "Mystery of the Hidden Key",
    "author": "Jane Smith",
    "popular": true,
    "favorites": true,
    "likesCount": 25,
    "dislikesCount": 2,
    "isLiked": true,
    "isDisliked": false
  },
  {
    "id": 3,
    "image": "https://images.unsplash.com/photo-1607473129014-0afb7ed09c3a?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "text": "Explore new cultures through the lens of our diverse non-fiction collection. Each book offers a unique insight into the world we live in, from personal memoirs to detailed historical accounts. Non-fiction is a powerful tool that brings to light the truths of our world, helping us understand the past, navigate the present, and shape the future. Our curated collection includes stories of triumph and tragedy, innovation and tradition, struggle and success. These books are not just about facts; they are about experiences, emotions, and the very essence of humanity. Whether you're interested in biographies of remarkable individuals, deep dives into scientific discoveries, or explorations of societal issues, our non-fiction selection is designed to inform and inspire. Reading these works will expand your horizons, challenge your perspectives, and enrich your knowledge. It’s an opportunity to walk in someone else’s shoes, see the world through their eyes, and emerge with a greater understanding of the complexities of life.",
    "date": "2022-01-03",
    "lesson_num": 3,
    "title": "Wonders of the World",
    "author": "Michael Brown",
    "popular": false,
    "favorites": false,
    "likesCount": 5,
    "dislikesCount": 0,
    "isLiked": false,
    "isDisliked": false
  },
  {
    "id": 4,
    "image": "https://images.unsplash.com/photo-1507738978512-35798112892c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "text": "Experience love and heartbreak with our curated romance novels. From timeless classics to modern love stories, our selection is sure to tug at your heartstrings. Romance novels have always held a special place in literature, offering readers an escape into the world of love, passion, and emotional connection. These stories explore the depths of human relationships, the joy of falling in love, and the pain of heartbreak. They remind us of the power of love and the impact it can have on our lives. Whether you’re in the mood for a light-hearted romantic comedy or a deep, emotional tale of love and loss, our collection has something to offer. These novels are more than just stories—they are journeys of the heart, where characters face challenges, overcome obstacles, and discover the true meaning of love. So, if you’re looking to get lost in a story that will make your heart race, bring a tear to your eye, or simply make you smile, dive into our romance section and find your next love story.",
    "date": "2022-01-04",
    "lesson_num": 4,
    "title": "Hearts Entwined",
    "author": "Emily Johnson",
    "popular": true,
    "favorites": true,
    "likesCount": 30,
    "dislikesCount": 3,
    "isLiked": true,
    "isDisliked": false
  },
  {
    "id": 5,
    "image": "https://images.unsplash.com/photo-1523865236457-3ae3358a4eaa?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "text": "Rediscover classic literature with our beautifully illustrated editions. These timeless tales, paired with stunning artwork, make for the perfect addition to any book lover’s collection. Classic literature holds the wisdom of ages and the beauty of masterful storytelling. These are the books that have shaped the literary world and continue to influence writers and readers alike. Our collection of classics includes works from some of the greatest authors in history, whose words have transcended time and culture. Each book is a treasure trove of rich language, complex characters, and profound themes that resonate across generations. The illustrated editions we offer bring these beloved stories to life in new ways, with artwork that enhances the reading experience and adds a visual dimension to the narratives. Whether you’re revisiting an old favorite or discovering a classic for the first time, these books are sure to inspire, educate, and entertain. Let these timeless tales remind you of the enduring power of literature.",
    "date": "2022-01-05",
    "lesson_num": 5,
    "title": "Pride and Prejudice",
    "author": "William Blake",
    "popular": false,
    "favorites": false,
    "likesCount": 8,
    "dislikesCount": 1,
    "isLiked": false,
    "isDisliked": false
  },
  {
    "id": 6,
    "image": "https://images.unsplash.com/photo-1521056787327-165dc2a32836?q=80&w=1925&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "text": "Unlock the secrets of the universe with our latest science fiction releases. These stories push the boundaries of imagination and explore the possibilities of the future. Science fiction is a genre that has always been at the forefront of exploring what could be, challenging our understanding of reality, and offering visions of the future that are both inspiring and terrifying. Our collection features works from authors who have mastered the art of blending scientific possibility with imaginative storytelling. These books delve into the unknown, exploring distant galaxies, futuristic societies, and the mysteries of time and space. They ask the big questions—what if?—and take you on journeys that stretch the limits of the mind. Whether you’re a seasoned sci-fi reader or new to the genre, you’ll find stories that will captivate your imagination, challenge your beliefs, and make you think about the future in new ways. Prepare to be transported to worlds beyond your wildest dreams, where anything is possible.",
    "date": "2022-01-06",
    "lesson_num": 6,
    "title": "The Final Frontier",
    "author": "David Clark",
    "popular": true,
    "favorites": true,
    "likesCount": 50,
    "dislikesCount": 5,
    "isLiked": true,
    "isDisliked": false
  },
  {
    "id": 7,
    "image": "https://images.unsplash.com/photo-1598618589695-e601731aed51?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "text": "Step into the past with our historical fiction bestsellers. These books bring history to life, offering a captivating blend of fact and fiction. Historical fiction is a genre that allows us to experience the past in a way that is both educational and entertaining. Our collection includes novels that transport you to different eras, from ancient civilizations to recent history, where real events and fictional stories intertwine. These books offer a unique perspective on history, giving life to characters and events that might otherwise be distant or abstract. They allow us to see the world as it was, understand the challenges people faced, and appreciate the complexities of historical events. Whether you’re interested in the grandeur of empires, the struggles of revolution, or the quiet moments of everyday life in the past, our historical fiction section has something for you. These stories will make you feel the weight of history, the joys and sorrows of those who lived through it, and the timeless lessons that still resonate today.",
    "date": "2022-01-07",
    "lesson_num": 7,
    "title": "The Lost Empire",
    "author": "Sophia Green",
    "popular": true,
    "favorites": false,
    "likesCount": 15,
    "dislikesCount": 1,
    "isLiked": true,
    "isDisliked": false
  },
  {
    "id": 8,
    "image": "https://images.unsplash.com/photo-1526170160160-1a5eb242ab58?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "text": "Embark on an epic adventure with our fantasy sagas. From dragons and wizards to epic battles, these stories are sure to captivate your imagination. Fantasy is a genre that allows readers to escape to worlds where the impossible becomes possible, where magic is real, and where heroes and villains engage in epic battles. Our collection of fantasy sagas features some of the most beloved series and standalone novels in the genre. These books take you on adventures through mystical lands, where dragons soar, wizards wield incredible powers, and brave warriors fight for the fate of kingdoms. The stories are filled with rich world-building, complex characters, and intricate plots that will keep you hooked from start to finish. Whether you’re a longtime fan of fantasy or just starting your journey into these magical realms, our selection has something for you. These tales will ignite your imagination, transport you to other worlds, and remind you of the limitless possibilities of storytelling.",
    "date": "2022-01-08",
    "lesson_num": 8,
    "title": "Dragon's Quest",
    "author": "James Williams",
    "popular": false,
    "favorites": true,
    "likesCount": 20,
    "dislikesCount": 3,
    "isLiked": true,
    "isDisliked": false
  },
  {
    "id": 9,
    "image": "https://images.unsplash.com/photo-1680449786212-de3b835dc467?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "text": "Challenge your mind with our selection of thought-provoking essays. These books offer deep insights and fresh perspectives on a variety of topics. Essays are a powerful form of literature that allows writers to explore complex ideas, challenge conventional wisdom, and provoke thought in their readers. Our collection of essays covers a wide range of topics, from philosophy and politics to personal reflections and cultural critiques. These works are designed to make you think, to question your assumptions, and to engage with the world in new ways. Whether you’re looking to dive deep into a particular subject or simply enjoy the art of the essay, our selection has something to offer. These books are not just for learning—they are for reflection, for conversation, and for expanding your understanding of the world. Reading essays is an intellectual journey, one that takes you through the minds of some of the greatest thinkers, offering you new ways to see and understand the world around you.",
    "date": "2022-01-09",
    "lesson_num": 9,
    "title": "Reflections on Life",
    "author": "Alexander Moore",
    "popular": true,
    "favorites": false,
    "likesCount": 12,
    "dislikesCount": 0,
    "isLiked": true,
    "isDisliked": false
  },
  {
    "id": 10,
    "image": "https://images.unsplash.com/photo-1505063366573-38928ae5567e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "text": "Get inspired with our collection of self-help and motivational books. Whether you’re looking to improve your mindset or achieve your goals, these books provide the guidance you need. Self-help and motivational books are more than just reading material—they are tools for personal growth and development. Our collection includes works from some of the most influential voices in the field, offering practical advice, inspirational stories, and strategies for success. These books cover a wide range of topics, from building confidence and overcoming obstacles to achieving your dreams and living a more fulfilling life. Whether you’re looking to improve your mental health, enhance your productivity, or simply find the motivation to pursue your goals, our self-help section has something for you. These books are not just about improving your life—they are about transforming it. They offer the guidance and support you need to become the best version of yourself, to unlock your full potential, and to live the life you’ve always dreamed of.",
    "date": "2022-01-10",
    "lesson_num": 10,
    "title": "The Power Within",
    "author": "Isabella Lewis",
    "popular": true,
    "favorites": true,
    "likesCount": 40,
    "dislikesCount": 2,
    "isLiked": true,
    "isDisliked": false
  }
]
